import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@shotly/ui/globals.css';
import { Toaster } from '@shotly/ui/components/sonner';

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} antialiased font-[family-name:var(--font-inter-sans)] has-data-[slot=sidebar-wrapper]:bg-sidebar`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
